// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkSMOJbR_b5_UIvdRv7dAoty6Twi6Bo4E',
    appId: '1:629145115004:web:0df2c15a8ae4d1970b6cf9',
    messagingSenderId: '629145115004',
    projectId: 'tcc-agenda-saude',
    authDomain: 'tcc-agenda-saude.firebaseapp.com',
    storageBucket: 'tcc-agenda-saude.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtbKwxIh48fokO0tzQ5jwH0eX2B4pUwBs',
    appId: '1:629145115004:android:bceec29e8412d2130b6cf9',
    messagingSenderId: '629145115004',
    projectId: 'tcc-agenda-saude',
    storageBucket: 'tcc-agenda-saude.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnwmM4bFImGbAud6GGMEitWBDg6Ko0qJg',
    appId: '1:629145115004:ios:a16167de7da426040b6cf9',
    messagingSenderId: '629145115004',
    projectId: 'tcc-agenda-saude',
    storageBucket: 'tcc-agenda-saude.firebasestorage.app',
    iosBundleId: 'com.example.agendaSaudeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnwmM4bFImGbAud6GGMEitWBDg6Ko0qJg',
    appId: '1:629145115004:ios:a16167de7da426040b6cf9',
    messagingSenderId: '629145115004',
    projectId: 'tcc-agenda-saude',
    storageBucket: 'tcc-agenda-saude.firebasestorage.app',
    iosBundleId: 'com.example.agendaSaudeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkSMOJbR_b5_UIvdRv7dAoty6Twi6Bo4E',
    appId: '1:629145115004:web:a6151349f7fe00550b6cf9',
    messagingSenderId: '629145115004',
    projectId: 'tcc-agenda-saude',
    authDomain: 'tcc-agenda-saude.firebaseapp.com',
    storageBucket: 'tcc-agenda-saude.firebasestorage.app',
  );
}
